repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.24.1
  hooks:
  - id: pyupgrade

- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
  - id: black
    language_version: python3
    description: 'Black formatting'

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
    description: 'Trims trailing whitespace'
  - id: end-of-file-fixer
    description: 'Makes sure files end in a new line and only a new line'
  - id: debug-statements
    description: 'Check for debugger imports and breakpoint'
  - id: check-merge-conflict
    description: 'Check for files that contain merge conflict strings'
  - id: mixed-line-ending
    description: 'Replaces or checks mixed line endings'
  - id: fix-encoding-pragma
    description: 'Add # -*- coding: utf-8 -*- to the top of python files'
  - id: name-tests-test
    description: 'verifies that test files are named correctly'

- repo: https://github.com/pycqa/pylint
  rev: pylint-2.6.0
  hooks:
  - id: pylint
    name: pylint
    language: system
    entry: pylint . ../wano_backend
    types: [python]
    always_run: true
    pass_filenames: false
