openapi: 3.0.0
info:
  description: Description des web services de Remoteprod
  version: "1.0.0"
  title: Wano Documentation
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "hammahadi2006@gmail.com"
  license:
    name: MHG-16
    url: https://opensource.org/licenses/MIT
tags:
- name: "authentication"
  description: "<p> Cet Api contient un service web de login ayant comme des entrées email et password d'un user
  <br/> il génére un access token  pour accéder les autres services web de plateforme</p>"
- name: User
  description: liste des web services d'user
paths:
  "/login":
    post:
      tags:
      - authentication
      summary: Avoir l'acces token pour pouvoir exécuter les autres webservices
      security:
      - wano_auth: []
      responses:
        '200':
          description: OK
        '400':
          description: Échoué. Demande mal comprise.
        '404':
          description: demande introuvable.
        '500':
          description: Erreur de serveur
  "/user/create":
    post:
      tags:
      - User
      summary: Creation d'un nouveau utilisateur
      requestBody:
        required: true
        content:
            application/json:
              schema:
                type: object
                required:
                    - first_name
                    - last_name
                    - email
                    - password
                    - tel
                    - user_status
                properties:
                  first_name:
                    type: "string"
                  last_name:
                    type: "string"
                  email:
                    type: "string"
                  password:
                    type: "string"
                  tel:
                    type: "string"
                  user_status:
                    type: "integer"
                    description: "User Status"
                    default: 1
                  date_of_birth:
                    type: "string"
      responses:
        '200':
          description: OK
        '400':
          description: Échoué. Demande mal comprise
        "409":
          description: Email existe
        "500":
          description: Erreur serveur

securityDefinitions:
  wano_auth:
    type: basic
  acess_Token:
    type: "apiKey"
    name: "idSession"
    in: "header"

security:
- acess_Token: []
